### ISSUE TITLE
[FEAT] `train` 및 `test` csv 개선

### ISSUE THREAD

**Issue by jagaldol** [boostcampaitech7/level2-nlp-generationfornlp-nlp-06-lv3#10]
### ⚠️ Please check for similar feature requests

- [X] 이전에 제안된 [기능 요청](https://github.com/boostcampaitech7/level2-nlp-generationfornlp-nlp-06-lv3/issues?q=+is%3Aissue+label%3A%22Type%3A+Enhancement%22+) 중 중복되는 것이 없습니다.

### 💡 기능 제목

정돈된 csv 파일 제작 및 현재 코드에서 적용

### 📄 기능 설명

`id`, `paragraph`, `problems`, `question_plus` 가 존재하는데 `problems` 안에 json으로 많은 값이 포함되어 있습니다.

```json
{
    "question": "(가)에 대한 설명으로 옳지 않은 것은?",
    "choices": [
        "고려 문종 때에 남경(南京)으로 승격되었다.",
        "종루(鐘樓), 이현, 칠패 등에서 상업활동이 이루어졌다.",
        "정도전은 궁궐 전각(殿閣)과 도성 성문 등의 이름을 지었다.",
        "성곽은 거중기 등을 이용하여 약 2년 만에 완성되었다."
    ],
    "answer": 1
}
```

이를 분해해서 각각의 컬럼으로 저장하려고 합니다.

---

또한, 불필요한 `question_plus` 컬럼을 삭제해보려고합니다.

`question_plus`의 경우 `train.csv`에는 존재하지 않고, `test.csv`에는 44개의 데이터에만 존재합니다. 이 44개의 데이터에 대해서 `question_plus`를 삭제하고 paragraph에 합치려고 합니다.

---

추가적으로 잘못되었다고 공지된 train.csv의 데이터도 삭제하겠습니다.

#### TODO

- [x] 새로운 `train.csv` 및 `test.csv` 제작
  - [x] `train.csv`, `test.csv` 컬럼 구조 변경
  - [x] `question_plus`로 포함되어야하는 데이터 이동
  - [x] 잘못된 train data 삭제
- [x] 기존 코드와의 호환성 수정
- [x] `train.csv`, `test.csv` 및 `baseline.ipynb` 수정하여 배포

### 🎯 기능 도입의 이점

좀더 정돈된 csv 파일을 얻을 수 있고, 이 csv 파일을 파싱하는 코드가 필요없어집니다. 이는 train 및 inference에서의 코드가 간략화 할 수 있으며, 데이터 분석에 대해서도 더 쉽게 접근할 수 있을 거 같습니다.

### ⚠️ 잠재적 문제

`question_plus`이 있는 44개의 경우에 대해서 데이터를 확인하였을 때 문제에 `<보기>`를 요구하고 있습니다. 따라서 `<보기>` + `question_plus` 까지 `paragraph`에 붙일 예정입니다.

가능하다면 보기를 따로 분리하는게 좋지만, 기존 train 및 test에 존재하는 paragraph에 포함된 보기 데이터를 분리해내기가 어려울 것 같아 일단은 paragraph 뒤에 붙일 예정입니다.

또한, 이렇게 `csv`를 수정했을 때, `main.py`나 `baseline.ipynb`과 호환이 되지 않기 때문에 이를 수정해서 배포해야할 것 같습니다.
