### ISSUE TITLE
[FEAT] LLM을 활용한 문제 유형 분석

### ISSUE THREAD

**Issue by gsgh3016** [boostcampaitech7/level2-nlp-generationfornlp-nlp-06-lv3#17]
### ⚠️ Please check for similar feature requests

- [X] 이전에 제안된 [기능 요청](https://github.com/boostcampaitech7/level2-nlp-generationfornlp-nlp-06-lv3/issues?q=+is%3Aissue+label%3A%22Type%3A+Enhancement%22+) 중 중복되는 것이 없습니다.

### 🏙️ 도입 배경

#29 이슈를 처리하기 앞서, train 데이터 정제 및 증강 논의가 있었습니다.
논의 과정에서 현재 프로젝트에서 데이터 정제와 증강이 정확히 어떤 작업인지 모호했고, #29 세부 문제 정의가 필요하다는 결론이 나왔습니다.
#29 세부 문제 정의 중 하나로 현재 이슈를 재오픈해 #29 작업을 위한 사전 작업을 실시하겠습니다.

### 📄 기능 설명

수능 문제 데이터를 LLM을 활용하여 문항 유형을 분류합니다.
분류 카테고리는 다음과 같습니다.

- 문제에서 제공된 정보로만 풀 수 있는 문항 &rarr;  **내부 추론**
- 외부 지식이 필요한 문항 &rarr; **외부 추론**

또한, 현재 프로젝트 및 이슈에서 데이터 정제와 증강 작업은 다음과 같습니다.

#### 데이터 정제
- 유형 변화 없음
- 문제 유형을 유지하며 기존 문제 의미가 더 명확해지도록 변경

#### 데이터 증강
- 유형 변화 있음
- 문제 유형을 변경하며 기존 문제에 정보를 추가 및 삭제하며 원본 데이터에 추가 

#### 데이터 증강

- 외부 추론 유형 문제에서 지문을 추가해 내부 추론 문제를 생성하는 작업은 해당 실험 및 기능 구현 후, #29 작업을 이어서 할 수 있습니다. 자세한 설명은 #29 이슈를 참고하세요.
- 내부 추론 문제에서 정보를 삭제하여 외부 추론 유형 문제를 생성하는 작업은 추후 진행하겠습니다. (이슈 오픈 시 링크 예정)

#### 데이터 정제

- 문제의 모호한 표현 등을 제거하는 데이터 정제 작업은 추후 진행하겠습니다. (이슈 오픈 시 링크 예정)

### 📋 TODO

- [x] 문제 유형(내부 추론, 외부 추론) 분류를 위한 프롬프트 설계 및 실험 
- [x] 전체 train 데이터 문제 유형 분류 실시
- [x] 분포 확인 및 시각화
- [ ] 분류 파이프라인 #29 이슈에 연결

### ⚠️ 잠재적 문제

- 프롬프트에 따른 성능이 예상보다 많이 달라질 수 있습니다.

### 🔗 관련 이슈

#29
