### ISSUE TITLE
[FEAT] 베이스라인 모듈화

### ISSUE THREAD

**Issue by sunvvis** [boostcampaitech7/level2-nlp-generationfornlp-nlp-06-lv3#19]
### ⚠️ Please check for similar feature requests

- [X] 이전에 제안된 [기능 요청](https://github.com/boostcampaitech7/level2-nlp-generationfornlp-nlp-06-lv3/issues?q=+is%3Aissue+label%3A%22Type%3A+Enhancement%22+) 중 중복되는 것이 없습니다.

### 💡 기능 제목

베이스라인 코드 구조 개선

#### TODO

1. 코드 구조 개선  
   - [x] `train.py`와 `inference.py` 분리  
   - [x] 유틸리티 함수를 정리하기 위한 `utils` 패키지 생성  

2. 프롬프트 관리  
   - [x] 프롬프트 관련 코드 분리  

3. 데이터 처리  
   - [x] 데이터 전처리와 로딩을 간소화하기 위한 `data_loader` 패키지 구현  

4. 모델 준비  
   - [x] #21
   - [x] 모델 및 토크나이저 설정 분리를 위한 `model_loader` 모듈 추가

5. 설정
    - [x] 하이퍼파라미터를 중앙화된 `config.yaml` 파일로 이동  
    - [x] 설정 파라미터 관리를 위한 `Config` 클래스 생성  

6. 평가 지표  
   - [x] 평가 지표 계산 및 관리를 위한 `metric` 모듈 추가  

7. 응답 처리  
   - [x] custom 모델 응답 템플릿 설계

### 🎯 기능 도입의 이점

- 원활한 협업
- 원활한 실험
- 코드 가독성 향상
- 관심사의 분리

### ⚠️ 잠재적 문제

많은 코드 수정 시 부작용으로 버그가 발생할 수 있음, 커밋 단위별 디버깅 필요
