### ISSUE TITLE
[FEAT] eval loss가 상승 시 학습 종료 구현

### ISSUE THREAD

**Issue by sunvvis** [boostcampaitech7/level2-nlp-generationfornlp-nlp-06-lv3#25]
### ⚠️ Please check for similar feature requests

- [x] 이전에 제안된 [기능 요청](https://github.com/boostcampaitech7/level2-nlp-generationfornlp-nlp-06-lv3/issues?q=+is%3Aissue+label%3A%22Type%3A+Enhancement%22+) 중 중복되는 것이 없습니다.

### 📄 기능 설명

early stop 기능을 사용하여 eval loss가 상승 시 과적합이라고 판단해 학습을 일찍 종료합니다.

### TODO

- [x] custom early stop class 구현
- [x] train.py에 early stop 적용
- [x] config.yaml에 파라미터 추가

### 🎯 기능 도입의 이점

- 학습 시 과적합 방지

### ⚠️ 잠재적 문제

- 모델의 한계 성능에 도달하지 못할 가능성 있음
