### ISSUE TITLE
[FEAT] 외부 지식을 활용한 문제에 지문을 추가하여 데이터 증강

### ISSUE THREAD

**Issue by gsgh3016** [boostcampaitech7/level2-nlp-generationfornlp-nlp-06-lv3#29]
### ⚠️ Please check for similar feature requests

- [X] 이전에 제안된 [기능 요청](https://github.com/boostcampaitech7/level2-nlp-generationfornlp-nlp-06-lv3/issues?q=+is%3Aissue+label%3A%22Type%3A+Enhancement%22+) 중 중복되는 것이 없습니다.

### 💡 기능 제목

위키피디아 API와 Paraphrasing을 활용한 문제 생성

### 📄 기능 설명

> 용어 정리
> 문제에서 제공된 정보로만 풀 수 있는 문항 → 내부 추론
> 외부 지식이 필요한 문항 → 외부 추론
> 데이터 증강: 문제 유형을 바꾸면서 새로운 문제를 생성하고 데이터에 추가
> #17 참조

외부 지식이 필요한 외부 추론 문제 &rarr; 문제에 필요한 지식이 있는 지문 생성 &rarr; 새로운 내부 추론 문제 생성 후 데이터에 추가

#### 📋 TODO

- [x] #17
- [x] #49
    - [x] 지문, 질문, 선지를 바탕으로 지문에 없는 문제 풀이 핵심 키워드 추출([관련 실험](https://chatgpt.com/share/67400e44-7378-800d-be94-718aab303c5e))
    - [x] 해당 키워드 위키피디아 페이지 존재 여부 필터링
- [x] #53
- [x] 생성된 지문과 기존 지문, 질문, 선지 검토
- [x] 데이터 저장 파이프라인 설계

### 🎯 기능 도입의 이점

- train 데이터를 바탕으로 다양한 유형의 문제를 생성할 수 있습니다.
- 추후 검색어 추출 방법을 변경해 새로운 데이터 증강을 시도할 수 있습니다.

### ⚠️ 잠재적 문제

- 지문 생성 시 프롬프트에 따른 gpt 4o mini의 안정성
- 생성된 지문과 기존 데이터의 조화 검토 시 데이터 오류 발생 가능

#### 완료된 작업
#17 #49 

#### 진행 중인 작업
#53
