### ISSUE TITLE
[FEAT] Retrieval-Augmented Generation 기능 구현

### ISSUE THREAD

**Issue by eyeol** [boostcampaitech7/level2-nlp-generationfornlp-nlp-06-lv3#40]
### ⚠️ Please check for similar feature requests

- [X] 이전에 제안된 [기능 요청](https://github.com/boostcampaitech7/level2-nlp-generationfornlp-nlp-06-lv3/issues?q=+is%3Aissue+label%3A%22Type%3A+Enhancement%22+) 중 중복되는 것이 없습니다.

### 💡 기능 요약

외부 데이터베이스와의 통합을 통해 학습된 모델의 정보 검색 및 응답 생성 성능을 향상시킴

### 📄 기능 설명

RAG를 도입해 학습된 모델이 외부 데이터베이스에서 관련 정보를 검색하고
이를 바탕으로 응답을 생성할 수 있도록 기능을 추가하고자 합니다.

### TODO
- [x] LangChain 기반 RAG 시스템 백본 작업
- [x] 벡터 데이터베이스(Vector DB) 구축
- ~[ ] Embedding Model 학습 및 설정~

> 시간이 허락한다면 BM25에 대한 추가적인 공부도 해보면 좋을것 같습니다.

### 🎯 기능 도입의 이점

- 학습된 모델이 데이터베이스에서 필요한 정보를 실시간으로 조회해, 더 정확한 답변 생성이 가능해질 것으로 기대됩니다.
- 특별히, KMMLU 같이 지문이 짧은 문제에 대한 해결 능력이 올라갈 것으로 예상됩니다.

### ⚠️ 잠재적 문제

- Retrieve해온 문서가 실질적인 문제 해결에 도움이 될지에 대한 의문이 있습니다.
- '도움이 될만한 문서'로 벡터 DB를 구성하는 것에 큰 어려움이 있을 것 같습니다.

해당 문제점들은 일단 개발을 하고 부딪히면서 하나하나 해결하겠습니다.
