### ISSUE TITLE
[FEAT] 데이터 버전 관리자

### ISSUE THREAD

**Issue by gsgh3016** [boostcampaitech7/level2-nlp-generationfornlp-nlp-06-lv3#57]
### ⚠️ Please check for similar feature requests

- [X] 이전에 제안된 [기능 요청](https://github.com/boostcampaitech7/level2-nlp-generationfornlp-nlp-06-lv3/issues?q=+is%3Aissue+label%3A%22Type%3A+Enhancement%22+) 중 중복되는 것이 없습니다.

### 💡 기능 요약

실험, 현재 데이터 상으로 최신 데이터를 로드하게 도와주는 관리자 기능 추가

### 📄 기능 설명

실험이 진행됨에 따라 `csv` 데이터가 많아집니다. 효율적인 관리를 위해서 데이터 컨벤션을 정했으니, 이를 바탕으로 최신 데이터를 로드하는 관리자를 만들면 하드 코딩 없이 데이터를 로드할 수 있습니다.

### TODO
- [x] 학습 및 추론에 사용되는 `train`, `valid`, `test` 데이터와 실험에 사용되는 `train_exp` 데이터 컨벤션 정리
- [x] 데이터 컨벤션에 따라 학습 및 추론, 데이터 증강에 사용되는 최신 데이터 파일 버전을 저장하는 yaml 파일 생성
- [x] 데이터 생성 및 실험에 따라 최신 데이터 파일 버전 yaml 을 업데이트
- [ ] (Optional) 사용자가 생성한 yaml 파일의 설정 값을 읽어서 데이터 관리자 ON/OFF 기능
- [ ] (Optional) 해당 기능을 학습/추론과 `Streamlit`에 적용

### 🎯 기능 도입의 이점

- 학습/추론 코드에도 해당 기능을 도입해서 데이터 버전 관리를 효율적으로 할 수 있습니다.
- 데이터 증강 시에도 해당 기능을 도입해서 데이터 증강 전체 과정을 자동화하기 용이합니다.
- 학습 및 추론을 위한 사용자 생성 yaml 파일로 데이터 관리자 ON/OFF

### ⚠️ 잠재적 문제

- 학습/추론에서 해당 기능을 적용할 경우, 담당 작업 팀원과 이야기가 필요합니다. @Usunwoo @jagaldol 
- 데이터 컨벤션이 적용되지 않은 파일의 경우, 해당 기능이 동작하지 않습니다.

### 🔗 관련 이슈

#35 #52
